// <auto-generated />
namespace Hackathon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_First_table_revision : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_First_table_revision));
        
        string IMigrationMetadata.Id
        {
            get { return "201702111633562_Added_First_table_revision"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
