// <auto-generated />
namespace Hackathon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class customer_email : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(customer_email));
        
        string IMigrationMetadata.Id
        {
            get { return "201702120310094_customer_email"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
