// <auto-generated />
namespace Hackathon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fix_initial_migration_ : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix_initial_migration_));
        
        string IMigrationMetadata.Id
        {
            get { return "201702111404172_fix_initial_migration_"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
